name: Python application

on:
  push:
    branches: [ "main"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint flake8 pytest
        if [ -f requirements_dev.txt ]; then pip install -r requirements_dev.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
    - name: Check if revision file was updated
      if: github.event_name == 'push' && contains(github.event.commits[0].added, 'revision.txt')
      run: |
        echo "Revision file was updated, generating new release..."
    - name: Extract latest version, release name, and body
      id: extract_release_vars
      run: |
        LATEST_VERSION=$(head -n 1 revision.txt | cut -d ":" -f 2- | tr -d " ")
        RELEASE_NAME=$(head -n 2 revision.txt | tail -n 1 | cut -d ":" -f 2- | tr -d " ")
        RELEASE_BODY=$(head -n 3 revision.txt | tail -n 1 | cut -d ":" -f 2- | tr -d " ")
        echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_ENV
        echo "RELEASE_NAME=$RELEASE_NAME" >> $GITHUB_ENV
        echo "RELEASE_BODY=$RELEASE_BODY" >> $GITHUB_ENV
    - name: Generate release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ env.LATEST_VERSION }}
        release_name: ${{ env.LATEST_VERSION }} ${{ env.RELEASE_NAME }}
        body: ${{ env.RELEASE_BODY }}
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}